In [3]:
import numpy as np

def determinant(matrix):
    try:
        det = np.linalg.det(matrix)
        return det
    except np.linalg.LinAlgError:
        print("The matrix is singular, and the determinant cannot be calculated.")

#I will input my matrix here
matrix = np.array([[1, 0, 1],
                   [0, 0, 1],
                   [1, 0, 1]])

result = determinant(matrix)

if result is not None:
    print(f"Determinant of the matrix:\n{matrix}\nis: {result}")

Determinant of the matrix:
[[1 0 1]
 [0 0 1]
 [1 0 1]]
is: 0.0


In [1]:
import numpy as np
#Code used to find all determinant 0 matrices




#defining the term "zero determinant"
def zero_determinant(matrix):
    return np.linalg.det(matrix) == 0
def generate_matrices_with_determinant_zero(empty_matrix):
    n = len(empty_matrix)
    #Here I simulate the game declaring the elements to be 1,0 and setting the degree of matrix as n
    elements = [1, 0]
    positions = [(i, j) for i in range(n) for j in range(n)]
    
    matrices_with_det_zero = set()  # Use a set to store unique matrices
    for perm in product_permutations(elements * (n * n // 2)):
        filled_matrix = empty_matrix.copy()
        for (i, j), value in zip(positions, perm):
            filled_matrix[i, j] = value
        
        if zero_determinant(filled_matrix):
            matrices_with_det_zero.add(tuple(map(tuple, filled_matrix.tolist())))

    return [np.array(matrix).tolist() for matrix in matrices_with_det_zero]
def product_permutations(iterable):
    if not iterable:
        return [[]]
    else:
        return [rest_perm + [x] for x in iterable for rest_perm in product_permutations(iterable[:iterable.index(x)] + iterable[iterable.index(x) + 1:])]

def print_matrices(matrices):
    for matrix in matrices:
        for row in matrix:
            print(row)
        print()

if __name__ == "__main__":
    n = int(input("Enter the size of the matrix (n x n): "))
    
    empty_matrix = np.zeros((n, n))


    matrices_with_det_zero = generate_matrices_with_determinant_zero(empty_matrix)

    print("\nMatrices with Determinant 0:")
    print_matrices(matrices_with_det_zero)


Enter the size of the matrix (n x n):  3



Matrices with Determinant 0:
[1.0, 0.0, 1.0]
[1.0, 0.0, 1.0]
[0.0, 0.0, 0.0]

[1.0, 1.0, 0.0]
[0.0, 1.0, 0.0]
[1.0, 0.0, 0.0]

[0.0, 1.0, 0.0]
[0.0, 1.0, 0.0]
[1.0, 1.0, 0.0]

[0.0, 0.0, 1.0]
[0.0, 1.0, 1.0]
[0.0, 1.0, 0.0]

[0.0, 1.0, 1.0]
[0.0, 0.0, 0.0]
[1.0, 1.0, 0.0]

[0.0, 0.0, 1.0]
[1.0, 0.0, 1.0]
[1.0, 0.0, 0.0]

[1.0, 1.0, 1.0]
[0.0, 0.0, 0.0]
[1.0, 0.0, 0.0]

[0.0, 0.0, 0.0]
[1.0, 1.0, 1.0]
[1.0, 0.0, 0.0]

[1.0, 1.0, 0.0]
[0.0, 1.0, 1.0]
[0.0, 0.0, 0.0]

[1.0, 1.0, 0.0]
[1.0, 0.0, 0.0]
[1.0, 0.0, 0.0]

[0.0, 1.0, 0.0]
[1.0, 0.0, 0.0]
[1.0, 1.0, 0.0]

[0.0, 1.0, 0.0]
[0.0, 1.0, 1.0]
[0.0, 1.0, 0.0]

[0.0, 0.0, 1.0]
[1.0, 1.0, 1.0]
[0.0, 0.0, 0.0]

[0.0, 1.0, 1.0]
[0.0, 1.0, 1.0]
[0.0, 0.0, 0.0]

[1.0, 1.0, 1.0]
[0.0, 0.0, 1.0]
[0.0, 0.0, 0.0]

[1.0, 0.0, 1.0]
[0.0, 0.0, 1.0]
[1.0, 0.0, 0.0]

[1.0, 0.0, 0.0]
[0.0, 1.0, 1.0]
[1.0, 0.0, 0.0]

[1.0, 0.0, 1.0]
[0.0, 1.0, 0.0]
[0.0, 1.0, 0.0]

[0.0, 1.0, 0.0]
[1.0, 1.0, 0.0]
[1.0, 0.0, 0.0]

[0.0, 1.0, 0.0]
[1.0, 1.0, 1.0]
[0.0, 0